apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis-2004-rt
  labels:
    app: iis-2004-rt
spec:
  replicas: 1
  template:
    metadata:
      name: iis-2004-rt
      labels:
        app: iis-2004-rt
    spec:
      runtimeClassName: windows-2004
      containers:
      - name: iis
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-2004
        resources:
          limits:
            cpu: 1
            memory: 800m
          requests:
            cpu: .1
            memory: 300m
        ports:
          - containerPort: 80
      nodeSelector:
        "kubernetes.io/os": windows
      tolerations:
        - key: ""
          operator: "Exists"
          effect: "NoSchedule"
  selector:
    matchLabels:
      app: iis-2004-rt
---
apiVersion: v1
kind: Service
metadata:
  name: iis
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: iis-2004-rt
