apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: e2eteam/busybox:1.29
    command:
      - sleep
      - "3600"
  restartPolicy: Always
  nodeSelector:
    "kubernetes.io/os": windows
  tolerations:
    - key: ""
      operator: "Exists"
      effect: "NoSchedule"
---
