apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  labels:
    app: logger
spec:
  replicas: 1
  template:
    metadata:
      name: logger
      labels:
        app: logger
    spec:
      containers:
        - command:
          - powershell.exe
          - -Command
          - sleep 10; $a="1234567890"; $a="$a-$a"; $a="$a-$a"; $a="$a-$a"; $a="$a-$a"; $a="$a-$a";
            $a="$a-$a"; $a="$a-$a"; $a="$a-$a"; $a="$a-$a"; $a="$a-$a"; $a="$a-$a"; $a="$a-$a";
            $a="$a-$a"; $a="$a-$a"; $a="$a-$a"; do { write-host "$(date)-$a"; sleep 0.1;
            } until($false)
          image: e2eteam/busybox:1.29
          imagePullPolicy: Always
          name: testwin
      nodeSelector:
        "kubernetes.io/os": windows
  selector:
    matchLabels:
      app: logger
---
apiVersion: v1
kind: Service
metadata:
  name: iis
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: logger
