apiVersion: v1
kind: Pod
metadata:
  name: test-hostnetwork
spec:
  # Requires NAT network called "host" set up on host (this is a hack... networking doesn't really work only)
  hostNetwork: true
  containers:
  - name: test
    image: e2eteam/busybox:1.29
    command:
      - sleep
      - "3600"
  restartPolicy: Always
  nodeSelector:
    "kubernetes.io/os": windows
  tolerations:
    - key: ""
      operator: "Exists"
      effect: "NoSchedule"
---