apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-windows-hostnetwork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami-windows-hostnetwork
  template:
    metadata:
      labels:
        app: whoami-windows-hostnetwork
    spec:
      hostNetwork: true
      containers:
      - image: stefanscherer/whoami:windows-amd64-2.0.1
        name: whoami-windows
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-windows-hostnetwork
  labels:
    app: whoami-windows-hostnetwork
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
  selector:
    app: whoami-windows-hostnetwork
  type: LoadBalancer