apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
  - name: test
    image: e2eteam/busybox:1.29
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: test-volume
      mountPath: /tmp/test
  restartPolicy: Always
  volumes:
  - name: test-volume
    emptyDir: {}
  nodeSelector:
    "kubernetes.io/os": windows