apiVersion: v1
kind: Pod
metadata:
  name: dns
spec:
  containers:
  - name: test
    image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
    command: ["cmd.exe"]
    args: ["/C", "for /l %x in (1, 1, 1000000) do nslookup google.com"]
  restartPolicy: Always
  nodeSelector:
    "kubernetes.io/os": windows
  tolerations:
    - key: ""
      operator: "Exists"
      effect: "NoSchedule"
---
