apiVersion: v1
kind: Pod
metadata:
  name: test
  # annotations:
  #   microsoft.com/hostprocess-inherit-user: "true"
spec:
  securityContext:
    windowsOptions:
      hostProcess: true
      runAsUserName: "NT AUTHORITY\\Local service"
  hostNetwork: true
  containers:
  - name: test
    imagePullPolicy: Always
    image: jsturtevant/busybox:1.29
    securityContext:
      windowsOptions:
        hostProcess: true
        runAsUserName: "NT AUTHORITY\\Local service"
    command:
      - ping
      - -t
      - 127.0.0.1
  restartPolicy: Always
  nodeSelector:
    "kubernetes.io/os": windows
  tolerations:
    - key: ""
      operator: "Exists"
      effect: "NoSchedule"
---
