apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-container
  template:
    metadata:
      labels:
        app: init-container
    spec:
      initContainers:
      - name: init-test
        image: e2eteam/busybox:1.29
        command:
        - cmd
        - /c
        - touch
        - c:\shared\somefile.txt
        - '&&'
        - cmd
        - /c
        - sleep
        - "60"
        - '&&'
        - cmd
        - /c
        - IF
        - NOT
        - EXIST
        - c:\shared\folder
        - mkdir
        - c:\shared\folder
        - '&&'
        - cmd
        - /c
        - curl.exe
        - -L
        - https://gist.githubusercontent.com/jsturtevant/a8caf0d86c8f5bf1d7a1800760b8bc95/raw/932a1019735e2b207e69dd057f5c16b5a97d8975/webrequest.ps1
        - -o
        - c:\shared\webrequest.ps1
        - '&&'
        - sleep
        - "40"
        volumeMounts:
          - mountPath: /shared
            name: shared-volume
      containers:
      - image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        name: main-container
        volumeMounts:
          - mountPath: /shared
            name: shared-volume
        lifecycle:
          postStart:
            exec:
              command:
              - cmd
              - /c
              - mklink
              - /d
              - c:\inetpub\wwwroot\testfolder
              - c:\shared\folder
              - '&&'
              - cmd
              - /c
              - mklink
              - c:\inetpub\wwwroot\somefile.txt
              - c:\shared\somefile.txt
              - '&&'
              - Powershell
              - c:\shared\webrequest.ps1
              - -url
              - http://bing.com
      nodeSelector:
        beta.kubernetes.io/os: windows
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: shared-volume
---
apiVersion: v1
kind: Service
metadata:
  name: init-container
  labels:
    app: init-container
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
  selector:
    app: init-container
  type: LoadBalancer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shared-volume
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shared-volume
  resources:
    requests:
      storage: 5Gi
