apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dns-utils
spec:
  containers:
    - name: util
      image: claudiubelu/dnsutils:1.1
      command: ["powershell", "sleep", "1000"]
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8