apiVersion: v1
kind: Service
metadata:
  name: nginx
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-mode: linuxpool2-availabilitySet-33087051
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
