apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-httpd
  template:
    metadata:
      labels:
        app: web-httpd
    spec:
      containers:
      - image: k8sprow.azurecr.io/kubernetes-e2e-test-images/httpd:2.4.39-alpine
        name: web-httpd
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: web-httpd
  labels:
    app: web-httpd
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: web-httpd
  type: LoadBalancer