name: k8s unit tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        repository: kubernetes/kubernetes

#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.16

#     - name: setup k8s for running tests on windows
#       run: go mod vendor

#     - name: Run fs util tests
#       run: |
#         cd pkg/volume/util/fs
#         go test . -mod=mod
    
    - name: Run proxy tests
      run: |
        get-netadatper
        get-vmswitch
        get-vm
#       cd pkg/proxy/winkernel
#       go test . -mod=mod

